export default {
    SIM_LIST: "/sim/search",
    WRITE_LIST: "/writeList/getWriteList",
    QUERY_WRITE_LIST_STATUS: "/writeList/queryWriteListStatus",
    SIM_IMPORT_SIMS: "/sim/importSims",
    SIM_EXPORT: "/sim/export",
    SIM_SYNC_UPDATE: "/sim/syncUpdate",
    SIM_GET_SIM: "/sim/getSim",
    SIM_UPDATE: "/sim/update",
    SIM_BATCH_UPDATE: "/sim/batchUpdate",
    SIM_BATCH_UPDATE_SIM_COMBO: "/sim/batchUpdateSimCombo",
    SIM_BATCH_UPDATE_SIM_USER: "/sim/batchUpdateSimUser",
    SIM_BATCH_UPDATE_SIM_ACTIVE_COMBO: "/sim/batchUpdateActiveCombo",
    SIM_TRANSFOR: "/sim/transfer",
    SIM_MIGRAT_SYNC_UPDATE: "/sim/migrationSyncUpdate",
    SIM_ICCID_SYNC_UPDATE: "/sim/iccidSyncUpdate",
    SIM_CONFIG_LIMT_VALUE: "/sim/configLimtValue",
    SIM_CONFIG_LIMT_VALUE_BY_SIMID: "/sim/configLimtValueBySimId",
    
}